spring.application.name=ProjetPrimeJSP

server.servlet.context-path=/ProjetPrimeJSP

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
# Je ne sais pas si cache = false est ok? spring.thymeleaf.cache=false


# Désactiver Spring Session JDBC ?
#spring.session.store-type=none

# === Logging / Debugging ===
#logging.level.org.springframework=TRACE
#logging.level.com=TRACE
server.error.include-message=always
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.bind=DEBUG


#le datasource École
#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=ProjetPrimeJSP; encrypt=true; trustServerCertificate=true
spring.datasource.url=jdbc:sqlserver://LAPTOP-GD0KDVGD\\SQLEXPRESS;databaseName=ProjetPrimeJSP; encrypt=true; trustServerCertificate=true

spring.datasource.username=loginDbEcommerce
spring.datasource.password=loginDbEcommerce
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#pour le framework Hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.type=trace

# définir la politique de nommage des colonnes dans la base de données
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
